// <auto-generated />
using System;
using Infraestrutura.Repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infraestrutura.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entidade.AdminEntidade.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataDeAtualizacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Admin", (string)null);
                });

            modelBuilder.Entity("Domain.Entidade.ProdutoEntidade.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AnoLancamentoProduto")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("Condicao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataDeAtualizacao")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EmbalagemProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmpresaProduto")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FormatoProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenerosMusicaisProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeArtistaBandaProduto")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("OrigemProduto")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("PrecoDescontoProduto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoProduto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("QuantidadeDeCancoesProduto")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeDiscos")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeProduto")
                        .HasColumnType("integer");

                    b.Property<string>("StatusProduto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDeAlbum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Domain.Entidade.ProdutoEntidade.Produto", b =>
                {
                    b.OwnsMany("Domain.Entidade.ProdutoEntidade.ArquivosProduto", "ArquivosProdutos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Ordem")
                                .HasColumnType("integer");

                            b1.Property<Guid>("ProdutoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PublicId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TipoArquivoProduto")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("ProdutoId");

                            b1.ToTable("ProdutoArquivos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.Navigation("ArquivosProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
