<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>22e64ea1-1330-4bdd-af46-90dc1a443854</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentResults" Version="3.16.0" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Factory\ProdutoFactory\Validacoes\" />
    </ItemGroup>

</Project>